services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=myfacturedb'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8083:8080'

  smtp4dev:
    image: 'rnwood/smtp4dev:v3'
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'


